//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.0
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from Automata.g4 by ANTLR 4.13.0

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="AutomataParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.0")]
[System.CLSCompliant(false)]
public interface IAutomataListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutomataParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSpecification([NotNull] AutomataParser.SpecificationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutomataParser.specification"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSpecification([NotNull] AutomataParser.SpecificationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutomataParser.states"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterStates([NotNull] AutomataParser.StatesContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutomataParser.states"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitStates([NotNull] AutomataParser.StatesContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="AutomataParser.state"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterState([NotNull] AutomataParser.StateContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="AutomataParser.state"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitState([NotNull] AutomataParser.StateContext context);
}
